#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64  : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : enable

#include "shared_structs.h"
#include "rng.glsl"

#define pi (3.141592)
#define pi2 (2.0*pi)

// The ray payload; structure is defined in shared_structs.h;
// Attached to a ray, and used to communicate between shader stages.
layout(location=0) rayPayloadEXT RayPayload payload;

// Push constant for ray tracing; structure is defined in shared_structs.h;
// Filled in by application, and pushed to shaders as part of the pipeline invocation
layout(push_constant) uniform _PushConstantRay { PushConstantRay pcRay; };

// Ray tracing descriptor set: 0:acceleration structure, and 1: color output image
layout(set=0, binding=0) uniform accelerationStructureEXT topLevelAS;
layout(set=0, binding=1, rgba32f) uniform image2D colCurr; // Output image: m_rtColCurrBuffer
// Many more buffers (at bindings 2 ... 7) will be added to this eventually.
layout( set = 0, binding = 2, scalar ) buffer _emitter { Emitter list[]; } emitter;

layout( set = 0, binding = 3, rgba32f ) uniform image2D KdCurr;
layout( set = 0, binding = 4, rgba32f ) uniform image2D NdCurr;
layout( set = 0, binding = 5, rgba32f ) uniform image2D ColPrev;
layout( set = 0, binding = 6, rgba32f ) uniform image2D KdPrev;
layout( set = 0, binding = 7, rgba32f ) uniform image2D NdPrev;

// Object model descriptor set: 0: matrices, 1:object buffer addresses, 2: texture list
layout(set=1, binding=0) uniform _MatrixUniforms { MatrixUniforms mats; };
layout(set=1, binding=1, scalar) buffer ObjDesc_ { ObjDesc i[]; } objDesc;
layout(set=1, binding=2) uniform sampler2D textureSamplers[];

// Object buffered data; dereferenced from ObjDesc addresses;  Must be global
layout(buffer_reference, scalar) buffer Vertices {Vertex v[]; }; // Position, normals, ..
layout(buffer_reference, scalar) buffer Indices {ivec3 i[]; }; // Triangle indices
layout(buffer_reference, scalar) buffer Materials {Material m[]; }; // Array of all materials
layout(buffer_reference, scalar) buffer MatIndices {int i[]; }; // Material ID for each triangle


struct PointOnLight 
{
    vec3 P;         // Point on light
    vec3 N;         // Normal at p
    float A;        // Area of triangle
    vec3 emission; // Emission of light
    uint index;     // Index of light in light-list
};

vec3 SampleLobe( vec3 A, float angle1, float angle2 )
{
    float s = sqrt( 1 - angle1 * angle1 );

    vec3 K = vec3( s * cos(angle2), s * sin(angle2), angle1 );

    if ( abs( A.z - 1 ) < .001 )
        return K;
    else if ( abs( A.z + 1 )  < .001 )
        return vec3( A.x, -A.y, -A.z );

    vec3 B = normalize( vec3( -A.y, A.x, 0 ) );
    vec3 C = cross( A, B );
    return K.x * B + K.y * C + K.z * A;
}

// @@ Raycasting: Write EvalBrdf -- The BRDF lighting calculation
vec3 EvalBrdf(vec3 N, vec3 L, vec3 V, Material mat) 
{ 
    /*
     *                     D(H) F(L, H) G(L, V, H)     K_d
     * BRDF = (N dot L) + ------------------------- + -----
     *                      4 (L dot N) (V dot N)      pi
     * 
     *         alpha + 2
     * D(H) = -----------(N dot H)^alpha
     *            2pi
     *
     * alpha = shininess
     *
     * F(L, H) = K_s + (1 - K_s)(1 - L dot H)^5
     *
     *      G(L, V, H)               1
     * -------------------- ~= -------------
     *  (L dot N)(V dot N)      (L dot H)^2
     *
     */

    vec3 LV = L + V;
    vec3 H = (LV) / length(LV);
    float dotLH = max( dot( L, H ), 0.0 );

    float termD = ( mat.shininess + 2 ) / ( pi2 ); 
    termD *= pow( max( dot( N, H ), 0.0 ), mat.shininess );

    vec3 termF = mat.specular + ( 1 - mat.specular ) * pow( 1 - dotLH, 5 );

    float termOcc = 1 / ( dotLH * dotLH );

    vec3 BRDF = mat.diffuse / pi + termD * termF * termOcc / 4;

    return BRDF;
}

// @@ Pathtracing: Write SampleBrdf, PdfBrdf, ...
vec3 SampleBrdf( inout uint seed, in vec3 N ) 
{ 
    return SampleLobe( N, sqrt( rnd(seed) ), pi2 * rnd(seed) );
}

float PdfBrdf( vec3 N, vec3 L )
{
    return abs( dot( N, L ) ) / pi;
}

vec3 SampleTriangle( vec3 A, vec3 B, vec3 C, uint seed )
{
    float b2 = rnd(seed);
    float b1 = rnd(seed);
    float b0 = 1 - b1 - b2;

    if ( b0 < 0 )
    {
        b1 = 1 - b1;
        b2 = 1 - b2;
        b0 = 1 - b1 - b2;
    }

    return b0 * A + b1 * B + b2 * C;
}

PointOnLight SampleLight( uint seed )
{
    PointOnLight pol = { vec3(0), vec3(0), 0, vec3(0), 0 };
    uint index = uint( rnd(seed) * emitter.list.length() );
    Emitter e = emitter.list[index];
    vec3 p = SampleTriangle( e.v0, e.v1, e.v2, seed );

    pol.P = p;
    pol.N = e.normal;
    pol.A = e.area;
    pol.emission = e.emission;
    pol.index = e.index;
    
    return pol;
}

float PdfLight( PointOnLight p ) 
{ 
    return 1.f / ( p.A * 1 );
}

vec3 EvalLight( PointOnLight p )
{
    return p.emission;
}

float GeometryFactor( vec3 Pa, vec3 Na, vec3 Pb, vec3 Nb )
{
    vec3 D = Pa - Pb;
    return abs( ( dot( D, Na ) * dot( D, Nb ) ) / ( dot( D, D ) * dot( D, D ) ) );
}

// and more

// Given a ray's payload indicating a triangle has been hit
// (payload.instanceIndex, and payload.primitiveIndex),
// lookup/calculate the material, texture and normal at the hit point
// from the three vertices of the hit triangle.
void GetHitObjectData(out Material mat, out vec3 nrm)
{
    // Object data (containing 4 device addresses)
    ObjDesc    objResources = objDesc.i[payload.instanceIndex];
    
    // Dereference the object's 4 device addresses
    Vertices   vertices    = Vertices(objResources.vertexAddress);
    Indices    indices     = Indices(objResources.indexAddress);
    Materials  materials   = Materials(objResources.materialAddress);
    MatIndices matIndices  = MatIndices(objResources.materialIndexAddress);
  
    // Use gl_PrimitiveID to access the triangle's vertices and material
    ivec3 ind    = indices.i[payload.primitiveIndex]; // The triangle hit
    int matIdx   = matIndices.i[payload.primitiveIndex]; // The triangles material index
    mat = materials.m[matIdx]; // The triangles material

    // Vertex of the triangle (Vertex has pos, nrm, tex)
    Vertex v0 = vertices.v[ind.x];
    Vertex v1 = vertices.v[ind.y];
    Vertex v2 = vertices.v[ind.z];

    // Compute normal at hit position using the provided barycentric coordinates.
    const vec3 bc = payload.bc; // The barycentric coordinates of the hit point
    nrm  = bc.x*v0.nrm + bc.y*v1.nrm + bc.z*v2.nrm; // Normal = combo of three vertex normals

    // If the material has a texture, read texture and use as the
    // point's diffuse color.
    if (mat.textureId >= 0) {
        vec2 uv =  bc.x*v0.texCoord + bc.y*v1.texCoord + bc.z*v2.texCoord;
        uint txtId = objResources.txtOffset + mat.textureId; // tex coord from three vertices
        mat.diffuse = texture(textureSamplers[(txtId)], uv).xyz; }
}

void main() 
{
    // Raycasting: Since the alignment of pcRay is SO easy to get wrong, test it
    // here and flag problems with a fully red screen.
    if (pcRay.alignmentTest != 1234) {
        imageStore(colCurr, ivec2(gl_LaunchIDEXT.xy), vec4(1,0,0,0));
        return; }
    
    // This shader's invocation is for the pixel indicated by
    // gl_LaunchIDEXT. Calculate that pixel's center (in NDC) and
    // convert to a ray in world coordinates.
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    vec2 pixelNDC = pixelCenter/vec2(gl_LaunchSizeEXT.xy)*2.0 - 1.0;
 
    vec3 eyeW    = (mats.viewInverse * vec4(0, 0, 0, 1)).xyz;
    vec4 pixelH = mats.viewInverse * mats.projInverse * vec4(pixelNDC.x, pixelNDC.y, 1, 1);
    vec3 pixelW = pixelH.xyz/pixelH.w;

    // This pixel's ray:
    vec3 rayOrigin    = eyeW;
    vec3 rayDirection = normalize(pixelW - eyeW);

    // The ray-casting / path-tracing block/loop will store the
    // pixel's calculated color in C.
    vec3 C = vec3(0,0,0);
    // The path tracing algorithm will accumulate a product of f/p weights in W.
    vec3 W = vec3(1,1,1);
    
    // @@ Pathtracing: Initialize random pixel seed *very* carefully! (See notes.)
    payload.seed = tea( gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, pcRay.frameSeed );
    // @@ History: Initialize first-hit data
    
    // @@ Raycasting: Notice that all the ray casting code is places
    // in this loop that's not really a loop since it executes only
    // once.  WHY?  Just looking ahead a bit into the next (path
    // tracing) project where this loop will actually loop.

    // @@ Pathtracing: Eventually, this will be the Monte-Carlo loop.
    bool firstHit;
    float firstDepth;
    vec3 firstNrm;
    vec3 firstKd;
    vec3 firstPos;

    for (int i=0; i<pcRay.depth;  i++)
    {
        payload.hit = false;
        // Fire the ray;  hit or miss shaders will be invoked, passing results back in the payload
        traceRayEXT(topLevelAS,           // acceleration structure
                    gl_RayFlagsOpaqueEXT, // rayFlags
                    0xFF,                 // cullMask
                    0,                    // sbtRecordOffset for the hitgroups
                    0,                    // sbtRecordStride for the hitgroups
                    0,                    // missIndex
                    rayOrigin,            // ray origin
                    0.001,                // ray min range
                    rayDirection,                 // ray direction
                    10000.0,              // ray max range
                    0                     // payload (location = 0)
                    );

        // If nothing was hit
        if (!payload.hit) 
        {
            // @@ Raycasting: break from the (wanna-be) loop
            // @@ Pathtracing: break from the Monte-Carlo loop
            firstHit = false;
            break;
            // @@ History: if (i==0) record that a first-hit did not occur
        }
        
        // If something was hit, find the object data.
        Material mat;
        vec3 nrm;
        GetHitObjectData(mat, nrm);
        
        if ( i == 0)
        {
            firstHit = payload.hit;
            firstDepth = payload.hitDist;
            firstNrm = normalize(nrm);
            firstKd = mat.diffuse;
            firstPos = payload.hitPos;
        }

        // @@ History: if (i==0) record first-hit stuff.
        // Test if the hit point's material is a light 
        if (dot(mat.emission,mat.emission) > 0.0) 
        {
            // @@ RayCasting: Accumulate (via C) the light's emission value
                // C += mat.emission*pcRay.exposure;
            // @@ Pathtracing: Accumulate (via C) the light's emission value
            //     times W (the product of the path's BRDFs)
                // C += W * mat.emission*pcRay.exposure;
            // @@ Explicit: Same as pathtracing, but with a factor of 1/2
                  C += 0.5 * W * mat.emission*pcRay.exposure;
            break; 
        }

        // @@ Explicit light connection (if implemented) goes here

        PointOnLight point = SampleLight(payload.seed);
        vec3 Wi = normalize( point.P - payload.hitPos );
        float dist = length(Wi);
        payload.hit = true;

        traceRayEXT
        (
            topLevelAS,
            gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT,
            0xff,
            0,
            0,
            0,
            payload.hitPos,
            0.001,
            Wi,
            dist - 0.001,
            0
        );

        if (!payload.hit)
        {
            vec3 N = normalize(nrm);
            vec3 Wo = -rayDirection;
            vec3 f = dot( N, Wi ) * EvalBrdf( N, Wi, Wo, mat );
            float p = PdfLight(point) / GeometryFactor( payload.hitPos, N, point.P, point.N );
            C += .5 * W * f / p * EvalLight(point);
        }
        
        // @@ Raycasting: Do lighting calculation here
            // vec3 N = normalize(nrm);
            // vec3 Wi = normalize( pcRay.scLightPos - payload.hitPos );
            // vec3 Wo = -rayDirection;
            // vec3 LIGHT = pcRay.scLightInt;

            // C += LIGHT * max( dot(N, Wi), 0 ) * EvalBrdf(N, Wi, Wo, mat);
        // Data for the calculation:
        //   Normal N = normalize(nrm) 
        //   Light input direction Wi = normalize(pcRay.scLightPos-payload.hitPos)
        //   Light output direction Wo = -rayDirection (Note the negation!)
        //   Light value from pcRay.scLightInt
        //   Material properties from mat possibly modified by a texture
        // As a great debugging aid. try C += abs(nrm); 

        // @@ Pathtracing:  Accumulate product of lighting calculations into W.
        //   Sample random direction Wi = ?
        //   Calculate f = (N dot Wi) * EvalBRDF(N, L, V, mat)
        //   Calculate p = ?
        //   Accumulate f/p into W;  No C += here anymore.
        //   Setup for next loop iteration.
        vec3 N = normalize(nrm);
        Wi = SampleBrdf( payload.seed, N );
        vec3 Wo = -rayDirection;

        vec3 f = dot( N, Wi ) * EvalBrdf( N, Wi, Wo, mat );
        float p = PdfBrdf( N, Wi ) * pcRay.rr;
        if ( p < .000001 )
            break;

        W *= f / p;

        rayOrigin = payload.hitPos;
        rayDirection = Wi;

        } // End of Monte-Carlo block/loop

    // @@ Raycasting: Write C to the output pixel
    //imageStore(colCurr, ivec2(gl_LaunchIDEXT.xy), vec4(C,1.0));
    // @@ Pathtracing: Accumulate C into output pixel.

    //vec4 old = imageLoad( colCurr, ivec2(gl_LaunchIDEXT) );
    vec4 old;
    vec2 screen;
    bool failure = false;

    if (firstHit)
    {
        vec4 screenH = ( mats.priorViewProj * vec4( firstPos, 1.0 ) );
        screen = ( ( screenH.xy / screenH.w ) + vec2(1.0) ) / 2.0;

        if ( ( screen.x > 1 || screen.x < 0 ) || ( screen.y > 1 || screen.y < 0 ) )
            failure = true;
    }
    else
        failure = true;

    if (!failure)
    {
        vec4 P;
        vec2 floc = screen * gl_LaunchSizeEXT.xy - vec2(.5);
        vec2 offset = fract(floc);
        ivec2 iloc = ivec2(floc);

        float B00 = ( 1 - offset.x ) * ( 1 - offset.y );
        float B01 = ( 1 - offset.x ) * (     offset.y );
        float B10 = (     offset.x ) * ( 1 - offset.y );
        float B11 = (     offset.x ) * (     offset.y );

        vec4 prevNd00 = imageLoad( NdPrev, iloc + ivec2( 0, 0 ) );
        vec4 prevNd01 = imageLoad( NdPrev, iloc + ivec2( 0, 1 ) );
        vec4 prevNd10 = imageLoad( NdPrev, iloc + ivec2( 1, 0 ) );
        vec4 prevNd11 = imageLoad( NdPrev, iloc + ivec2( 1, 1 ) );

        float dWeight00 = abs( firstDepth - prevNd00.w ) < .15 ? 1 : 0; 
        float dWeight01 = abs( firstDepth - prevNd01.w ) < .15 ? 1 : 0; 
        float dWeight10 = abs( firstDepth - prevNd10.w ) < .15 ? 1 : 0; 
        float dWeight11 = abs( firstDepth - prevNd11.w ) < .15 ? 1 : 0; 

        float nWeight00 = abs( dot( firstNrm, prevNd00.xyz ) ) > .95 ? 1 : 0;
        float nWeight01 = abs( dot( firstNrm, prevNd01.xyz ) ) > .95 ? 1 : 0;
        float nWeight10 = abs( dot( firstNrm, prevNd10.xyz ) ) > .95 ? 1 : 0;
        float nWeight11 = abs( dot( firstNrm, prevNd11.xyz ) ) > .95 ? 1 : 0;

        float w00 = B00 * dWeight00 * nWeight00;
        float w01 = B01 * dWeight01 * nWeight01;
        float w10 = B10 * dWeight10 * nWeight10;
        float w11 = B11 * dWeight11 * nWeight11;

        float weight = w00 + w01 + w10 + w11;
        if (weight != 0)
        {
            P  = w00 * imageLoad( ColPrev, iloc + ivec2( 0, 0 ) ); 
            P += w01 * imageLoad( ColPrev, iloc + ivec2( 0, 1 ) ); 
            P += w10 * imageLoad( ColPrev, iloc + ivec2( 1, 0 ) ); 
            P += w11 * imageLoad( ColPrev, iloc + ivec2( 1, 1 ) ); 
            P /= weight;
            old = P;
        }
        else
            failure = true;
    }

    if (failure)
        old = vec4( .5, .5, .5, 1 );

    float N = old.w + 1;
    vec3 Ave = old.xyz + ( C - old.xyz ) / N;

    if ( !any( isnan(Ave) ) && !any( isinf(Ave) ) && !isnan(N) && !isinf(N) )
        imageStore( colCurr, ivec2(gl_LaunchIDEXT), vec4( Ave, N ) );

    if ( !any( isnan(firstKd) ) && !any( isinf(firstKd ) ) )
        imageStore( KdCurr, ivec2(gl_LaunchIDEXT.xy), vec4( firstKd, 0 ) );

    if ( !any( isnan(firstNrm) ) && !any( isinf(firstNrm) ) && !isnan(firstDepth) && !isinf(firstDepth) )
        imageStore( NdCurr, ivec2(gl_LaunchIDEXT.xy), vec4( firstNrm, firstDepth ) );
    // @@ History: Accumulate C with a back-projected pixel and write to the output pixel

}

//  LocalWords:  Pathtracing Raycasting
